### ISSUE TITLE
try-catch around module import

### ISSUE THREAD

**Issue by tfc** [klau2005/prometheus_generic_exporter#1]
Hi there,

i am currently in the process of checking out your great tool and found a thing that reduces the user experience:

There is a try-catch clause around the module imports that tells the user that *some* module could not be loaded and then quits the script with an error value.
I suggest removing that try-catch block around the imports, because:

- as a user i am then told by the python interpreter *which* dependency is missing
- the script exits with an error value anyway, even without the try-catch.

That would improve the first user experience.

**Comment by klau2005** [comment]
Hi @tfc ,

Thanks for the suggestion, it makes perfect sense to actually be notified what modules are missing instead of receiving a generic message.

P.S. I don't know what issues I have with the email notifications from GitHub, I didn't receive any regarding this...

Claudiu
